#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer Auto Loader...
if (file_exists($autoloader = __DIR__.'/vendor/autoload.php')) {
    require $autoloader;
}

/** @var \Illuminate\Foundation\Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

if (method_exists($app, 'handleCommand')) {
    $status = $app->handleCommand(
        new \Symfony\Component\Console\Input\ArgvInput
    );
    exit($status);
}

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
