@extends('layouts.dashboard')

@section('title', 'Smart Flashcards - AI Study Assistant')

@section('content')
<div class="container-fluid px-0">
    <!-- Header -->
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-3">
        <div>
            <h2 class="fw-bold text-dark mb-1">Smart Flashcards Deck</h2>
            <p class="text-muted mb-0">Review key definitions, terms, and concept cards generated by AI.</p>
        </div>
        <div class="d-flex gap-2">
            <a href="{{ route('flashcards.review') }}" class="btn btn-success d-inline-flex align-items-center gap-2 shadow-sm">
                <i class="bi bi-play-circle-fill fs-5"></i>
                <span>Start Interactive Review</span>
            </a>
            <a href="{{ route('flashcards.create') }}" class="btn btn-primary-custom d-inline-flex align-items-center gap-2 shadow-sm">
                <i class="bi bi-plus-lg"></i>
                <span>Generate New Deck</span>
            </a>
        </div>
    </div>

    <!-- Stats & Filters -->
    <div class="row g-3 mb-4">
        <div class="col-md-4">
            <div class="card card-custom p-3 bg-white d-flex flex-row align-items-center gap-3">
                <div class="bg-primary-subtle text-primary rounded p-3">
                    <i class="bi bi-card-heading fs-3"></i>
                </div>
                <div>
                    <h3 class="fw-bold mb-0 text-dark">{{ $flashcards->count() }}</h3>
                    <small class="text-muted">Total Flashcards</small>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card card-custom p-3 bg-white d-flex flex-row align-items-center gap-3">
                <div class="bg-warning-subtle text-warning rounded p-3">
                    <i class="bi bi-star-fill fs-3"></i>
                </div>
                <div>
                    <h3 class="fw-bold mb-0 text-dark">{{ $totalFavorites }}</h3>
                    <small class="text-muted">Starred Favorites</small>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card card-custom p-3 bg-white d-flex align-items-center justify-content-center">
                <a href="{{ route('flashcards.review', ['favorites' => 1]) }}" class="btn btn-outline-warning w-100 py-2 fw-semibold">
                    <i class="bi bi-star-fill me-1"></i> Review Starred Cards Only
                </a>
            </div>
        </div>
    </div>

    <!-- Cards Grid -->
    @if($flashcards->count() > 0)
        <div class="row g-4 mb-4">
            @foreach($flashcards as $card)
                <div class="col-md-6 col-lg-4">
                    <div class="card card-custom bg-white p-4 h-100 border d-flex flex-column justify-between">
                        <div>
                            <div class="d-flex justify-content-between align-items-start mb-2">
                                <span class="badge bg-light text-dark border">
                                    <i class="bi bi-eye me-1"></i>Reviewed {{ $card->review_count }}x
                                </span>
                                <form method="POST" action="{{ route('flashcards.favorite', $card) }}" class="d-inline">
                                    @csrf
                                    <button type="submit" class="btn btn-link p-0 text-decoration-none fs-5 border-0">
                                        <i class="bi {{ $card->is_favorite ? 'bi-star-fill text-warning' : 'bi-star text-muted' }}"></i>
                                    </button>
                                </form>
                            </div>

                            <h6 class="fw-bold text-primary mb-2">Question / Term:</h6>
                            <p class="fw-semibold text-dark mb-3 fs-6">
                                {{ Str::limit($card->question, 90) }}
                            </p>

                            <h6 class="fw-bold text-secondary mb-1 fs-7">Answer:</h6>
                            <p class="text-muted fs-7 mb-0">
                                {{ Str::limit($card->answer, 110) }}
                            </p>
                        </div>

                        <div class="pt-3 border-top d-flex justify-content-between align-items-center mt-3">
                            <small class="text-muted fs-8">
                                {{ $card->last_reviewed_at ? 'Last review ' . $card->last_reviewed_at->diffForHumans() : 'Not reviewed yet' }}
                            </small>

                            <form method="POST" action="{{ route('flashcards.destroy', $card) }}" onsubmit="return confirm('Delete this card?');">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-light text-danger"><i class="bi bi-trash"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @else
        <div class="card card-custom p-5 text-center bg-white border">
            <div class="bg-primary-subtle text-primary rounded-circle d-inline-flex p-3 mx-auto mb-3" style="width: 64px; height: 64px; justify-content: center; align-items: center;">
                <i class="bi bi-card-heading fs-2"></i>
            </div>
            <h4 class="fw-bold text-dark mb-2">No Flashcards Available</h4>
            <p class="text-muted mb-4" style="max-width: 450px; margin: 0 auto;">
                Generate interactive flashcards from your study materials or summaries with AI.
            </p>
            <div>
                <a href="{{ route('flashcards.create') }}" class="btn btn-primary-custom px-4 py-2">
                    <i class="bi bi-plus-lg me-1"></i> Create Flashcard Deck
                </a>
            </div>
        </div>
    @endif
</div>
@endsection
